version: '3.8'

services:
  authentication-gateway:
    image: node:18-alpine
    user: ${USERID}
    working_dir: /var/workspace
    volumes:
      - ${DEV_OVERLAY_DIR}:/var/workspace/:cached
    ports:
      - "3000:3000" # nodejs express server application port to access it directly
      - "9229:9229" # nodejs debugger port
    environment:
      # KEYCLOAK_SERVER_ADDRESS: "http://keycloak:8080"
      
      # KEYCLOAK_DOTBASE_REALM_NAME: "dotbase"
      # KEYCLOAK_DOTBASE_REALM_CLIENT_ID: "authentication-gateway"
      # KEYCLOAK_DOTBASE_REALM_CLIENT_SECRET: ""
      # DOTBASE_REALM_COOKIE_ENCRYPTION_PASSPHRASE_AES: ""
      
      # KEYCLOAK_PATIENT_REALM_NAME: "patients"
      # KEYCLOAK_PATIENT_REALM_CLIENT_ID: "authentication-gateway"
      # KEYCLOAK_PATIENT_REALM_CLIENT_SECRET: ""
      # PATIENT_REALM_COOKIE_ENCRYPTION_PASSPHRASE_AES: ""
    command:
      - sleep
      - infinity
